const defaultIngredients = [
  { id: "chicken-breast", name: "Chicken Breast" },
  { id: "ground-beef", name: "Ground Beef" },
  { id: "italian-sausage", name: "Italian Sausage" },
  { id: "bacon", name: "Bacon" },
  { id: "rotisserie-chicken", name: "Rotisserie Chicken" },
  { id: "onion", name: "Onion" },
  { id: "garlic", name: "Garlic" },
  { id: "carrots", name: "Carrots" },
  { id: "celery", name: "Celery" },
  { id: "potatoes", name: "Potatoes" },
  { id: "butter", name: "Butter" },
  { id: "milk", name: "Milk" },
  { id: "heavy-cream", name: "Heavy Cream" },
  { id: "half-and-half", name: "Half and Half" },
  { id: "chicken-broth", name: "Chicken Broth" },
  { id: "chicken-stock", name: "Chicken Stock" },
  { id: "beef-stock", name: "Beef Stock" },
  { id: "cheddar-cheese", name: "Cheddar Cheese" },
  { id: "mozzarella", name: "Mozzarella" },
  { id: "parmesan", name: "Parmesan" },
  { id: "cream-cheese", name: "Cream Cheese" },
  { id: "tortillas", name: "Tortillas" },
  { id: "rice", name: "Rice" },
  { id: "orzo", name: "Orzo" },
  { id: "lasagna-noodles", name: "Lasagna Noodles" },
  { id: "spaghetti", name: "Spaghetti" },
  { id: "bowtie-pasta", name: "Bowtie Pasta" },
  { id: "ravioli", name: "Ravioli" },
  { id: "bell-peppers", name: "Bell Peppers" },
  { id: "spinach", name: "Spinach" },
  { id: "black-beans", name: "Black Beans" },
  { id: "corn", name: "Corn" },
  { id: "tomatoes", name: "Tomatoes" },
  { id: "flour", name: "Flour" },
  { id: "brown-sugar", name: "Brown Sugar" },
  { id: "oats", name: "Oats" },
  { id: "chia-seeds", name: "Chia Seeds" },
  { id: "peanut-butter", name: "Peanut Butter" },
  { id: "protein-powder", name: "Protein Powder" },
  { id: "eggs", name: "Eggs" }
];